import { exo2Font } from "@/app/font"
import Navbar from "@/components/navbar/navbar"
import type { Metadata } from "next"
import React from "react"
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${exo2Font.className} bg-black text-white`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
